# Generated by Django 4.2.29 on 2026-03-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessEvent',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID события')),
                ('external_event_id', models.CharField(blank=True, help_text='UUID из внешней системы — для защиты от дубликатов', max_length=100, null=True, unique=True, verbose_name='Внешний ID события')),
                ('event_type_code', models.CharField(choices=[('batch.received', 'Партия принята на склад'), ('batch.placed', 'Партия размещена в ячейке'), ('batch.moved', 'Партия перемещена'), ('batch.reserved', 'Партия зарезервирована'), ('order.created', 'Заказ создан'), ('order.picking_started', 'Начата комплектация'), ('order.item_picked', 'Позиция подобрана'), ('order.assembled', 'Комплектация завершена'), ('shipment.dispatched', 'Отгрузка выполнена'), ('location.blocked', 'Локация заблокирована'), ('location.unblocked', 'Локация разблокирована')], max_length=50, verbose_name='Тип события')),
                ('source_system', models.CharField(help_text='Например: scanner, simulator, import, manual', max_length=100, verbose_name='Источник события')),
                ('event_time', models.DateTimeField(help_text='Момент фактического возникновения события в процессе', verbose_name='Время возникновения события')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Время получения системой')),
                ('new_stage_code', models.CharField(blank=True, help_text='Код этапа, в который перешёл объект после события', max_length=50, null=True, verbose_name='Новый этап объекта')),
                ('processing_status', models.CharField(choices=[('received', 'Получено'), ('accepted', 'Принято'), ('rejected', 'Отклонено'), ('applied', 'Применено')], default='received', max_length=30, verbose_name='Статус обработки')),
                ('payload_json', models.JSONField(blank=True, help_text='Дополнительные атрибуты события, зависящие от event_type', null=True, verbose_name='Полезная нагрузка (JSON)')),
            ],
            options={
                'verbose_name': 'Событие процесса',
                'verbose_name_plural': 'События процесса',
                'db_table': 'process_event',
                'ordering': ['-event_time'],
            },
        ),
    ]
