# Generated by Django 4.2.29 on 2026-03-20 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('events', '0001_initial'),
        ('references', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processevent',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='inventory.batch', verbose_name='Партия'),
        ),
        migrations.AddField(
            model_name='processevent',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='references.storagelocation', verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='processevent',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='orders.customerorder', verbose_name='Заказ'),
        ),
        migrations.AddIndex(
            model_name='processevent',
            index=models.Index(fields=['event_type_code'], name='idx_event_type'),
        ),
        migrations.AddIndex(
            model_name='processevent',
            index=models.Index(fields=['event_time'], name='idx_event_time'),
        ),
        migrations.AddIndex(
            model_name='processevent',
            index=models.Index(fields=['batch'], name='idx_event_batch'),
        ),
        migrations.AddIndex(
            model_name='processevent',
            index=models.Index(fields=['order'], name='idx_event_order'),
        ),
        migrations.AddIndex(
            model_name='processevent',
            index=models.Index(fields=['processing_status'], name='idx_event_status'),
        ),
    ]
