# Generated by Django 4.2.29 on 2026-03-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processevent',
            name='event_type_code',
            field=models.CharField(choices=[('batch.received', 'Партия принята на склад'), ('batch.placed', 'Партия размещена в ячейке'), ('batch.moved', 'Партия перемещена'), ('batch.reserved', 'Партия зарезервирована'), ('order.created', 'Заказ создан'), ('order.picking_started', 'Начата комплектация'), ('order.item_picked', 'Позиция подобрана'), ('order.assembled', 'Комплектация завершена'), ('shipment.dispatched', 'Отгрузка выполнена')], max_length=50, verbose_name='Тип события'),
        ),
    ]
