# Generated by Django 4.2.29 on 2026-03-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID товара')),
                ('sku_code', models.CharField(help_text='Уникальный внутренний код товарной позиции', max_length=50, unique=True, verbose_name='Код SKU')),
                ('product_name', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('unit_of_measure', models.CharField(help_text='Например: шт, кг, л, м', max_length=20, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'product',
                'ordering': ['sku_code'],
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('location_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID локации')),
                ('location_code', models.CharField(help_text='Уникальный код складской локации, например: A-01-03', max_length=50, unique=True, verbose_name='Код локации')),
                ('location_name', models.CharField(max_length=255, verbose_name='Название локации')),
                ('location_type', models.CharField(choices=[('receiving', 'Зона приёмки'), ('storage', 'Зона хранения'), ('picking', 'Зона комплектации'), ('buffer', 'Буферная зона'), ('shipping', 'Зона отгрузки')], max_length=50, verbose_name='Тип локации')),
            ],
            options={
                'verbose_name': 'Складская локация',
                'verbose_name_plural': 'Складские локации',
                'db_table': 'storage_location',
                'ordering': ['location_code'],
            },
        ),
    ]
