# Generated by Django 4.2.29 on 2026-03-20 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID заказа')),
                ('order_number', models.CharField(help_text='Уникальный номер заказа, например: ORD-2026-0001', max_length=50, unique=True, verbose_name='Номер заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('planned_ship_date', models.DateTimeField(blank=True, null=True, verbose_name='Плановая дата отгрузки')),
                ('priority_code', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='normal', max_length=20, verbose_name='Приоритет')),
                ('current_stage_code', models.CharField(choices=[('created', 'Создан'), ('queued', 'В очереди'), ('picking', 'Комплектация'), ('assembled', 'Скомплектован'), ('shipped', 'Отгружен'), ('closed', 'Закрыт'), ('cancelled', 'Отменён')], default='created', max_length=50, verbose_name='Текущий этап')),
                ('completion_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процент выполнения')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('last_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.processevent', verbose_name='Последнее событие')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'customer_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('order_line_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID строки заказа')),
                ('requested_qty', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Требуемое количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.customerorder', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='references.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Строка заказа',
                'verbose_name_plural': 'Строки заказа',
                'db_table': 'order_line',
            },
        ),
    ]
