# Generated by Django 4.2.29 on 2026-03-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_customerorder_current_stage_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='current_stage_code',
            field=models.CharField(choices=[('created', 'Создан'), ('picking', 'Комплектация'), ('assembled', 'Скомплектован'), ('shipped', 'Отгружен')], default='created', max_length=50, verbose_name='Текущий этап'),
        ),
    ]
