# Generated by Django 4.2.29 on 2026-03-20 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
        ('events', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID партии')),
                ('batch_number', models.CharField(help_text='Уникальный номер партии, например: BATCH-00045', max_length=50, unique=True, verbose_name='Номер партии')),
                ('quantity_total', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Общее количество')),
                ('quantity_reserved', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Зарезервировано')),
                ('quantity_picked', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Подобрано')),
                ('quantity_shipped', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Отгружено')),
                ('current_stage_code', models.CharField(choices=[('expected', 'Ожидает приёмки'), ('received', 'Принята'), ('placed', 'Размещена'), ('stored', 'На хранении'), ('reserved', 'Зарезервирована'), ('picked', 'Подобрана'), ('shipped', 'Отгружена'), ('closed', 'Закрыта')], default='expected', max_length=50, verbose_name='Текущий этап')),
                ('receipt_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата поступления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('current_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='references.storagelocation', verbose_name='Текущая локация')),
                ('last_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.processevent', verbose_name='Последнее событие')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='references.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Партия',
                'verbose_name_plural': 'Партии',
                'db_table': 'batch',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchReservation',
            fields=[
                ('reservation_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID резервирования')),
                ('reserved_qty', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Зарезервировано')),
                ('picked_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Подобрано')),
                ('reservation_status', models.CharField(choices=[('active', 'Активно'), ('picking', 'В комплектации'), ('picked', 'Подобрано'), ('shipped', 'Отгружено'), ('cancelled', 'Отменено')], default='active', max_length=30, verbose_name='Статус резервирования')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.batch', verbose_name='Партия')),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='orders.orderline', verbose_name='Строка заказа')),
            ],
            options={
                'verbose_name': 'Резервирование партии',
                'verbose_name_plural': 'Резервирования партий',
                'db_table': 'batch_reservation',
            },
        ),
    ]
