# Generated by Django 4.2.29 on 2026-03-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='current_stage_code',
            field=models.CharField(choices=[('expected', 'Ожидает приёмки'), ('received', 'Принята'), ('placed', 'Размещена'), ('stored', 'На хранении'), ('reserved', 'Зарезервирована'), ('shipped', 'Отгружена')], default='expected', max_length=50, verbose_name='Текущий этап'),
        ),
    ]
